In [1]:
import pandas as pd
import numpy as np

In [2]:
date = pd.read_csv("./orders.csv")
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [3]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [4]:
date["date"] = pd.to_datetime(date["date"])

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [6]:
date["year"] = date["date"].dt.year
date.head()

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019

In [7]:
date["month"] = date["date"].dt.month
date.head()

        date  product_id  city_id  orders  year  month
0 2019-12-10        5628       25       3  2019     12
1 2018-08-15        3646       14     157  2018      8
2 2018-10-23        1859       25       1  2018     10
3 2019-08-17        7292       25       1  2019      8
4 2019-01-06        4344       25       3  2019      1

In [8]:
date["month_name"] = date["date"].dt.month_name()
date.head()

        date  product_id  city_id  orders  year  month month_name
0 2019-12-10        5628       25       3  2019     12   December
1 2018-08-15        3646       14     157  2018      8     August
2 2018-10-23        1859       25       1  2018     10    October
3 2019-08-17        7292       25       1  2019      8     August
4 2019-01-06        4344       25       3  2019      1    January

In [9]:
date["date_day"] = date["date"].dt.day
date.head()

        date  product_id  city_id  orders  year  month month_name  date_day
0 2019-12-10        5628       25       3  2019     12   December        10
1 2018-08-15        3646       14     157  2018      8     August        15
2 2018-10-23        1859       25       1  2018     10    October        23
3 2019-08-17        7292       25       1  2019      8     August        17
4 2019-01-06        4344       25       3  2019      1    January         6

In [10]:
date["day_name"] = date["date"].dt.day_name()
date.head()

,date,product_id,city_id,orders,year,month,month_name,date_day,day_name
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday

In [14]:
date["is_weekend"] = np.where(date["day_name"].isin(["Saturday", "Sunday"]), 1, 0)
date.head()

,date,product_id,city_id,orders,year,month,month_name,date_day,day_name,is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,1

In [15]:
time = pd.read_csv("./messages.csv")
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [16]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [17]:
time["date"] = pd.to_datetime(time["date"])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [23]:
time["hour"] = time["date"].dt.hour
time["min"] = time["date"].dt.minute
time["sec"] = time["date"].dt.second

In [22]:
time.head(25)

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0
5,2016-03-08 22:52:00,пар.32прок.дев.на авто по ночн.городу.Днепр.06...,22,52,0
6,2014-02-18 00:23:00,Семейная пара познакомится для отношений,0,23,0
7,2012-11-23 01:10:00,ДЛЯ С.П СНАЧАЛО СМС 066.679.400.8,1,10,0
8,2014-12-23 01:20:00,Дедушки ау вы где? СНЕГУРОЧКИ СКУЧАЮТ. Здесь е...,1,20,0
9,2012-11-03 23:46:00,ищу парня с авто.063 528 90 72,23,46,0
10,2013-07-26 00:11:00,Хочу обшения на инт темы с девушкой 0500747823...,0,11,0
11,2013-12-18 00:39:00,открою дверь прохожему который хочет погреться...,0,39,0
12,2013-06-05 01:05:00,.эксперементаторше. 0678676246,1,5,0
13,2016-11-27 22:29:00,Полненькая девушка ищет парня для серн.отн.Али...,22,29,0
14,2015-10-04 01:42:00,парень ищет общения. 099,1,42,0
15,2012-08-24 23:13:00,Саша 4 Я знаю все о твоих письмах.Сколько это ...,23,13,0
16,2015-10-19 22:52:00,КТО СДЕЛАЕТ ПАРНЮ МАССАЖ ДЕВ ИЛИ 2 СЕЙЧАС 099 ...,22,52,0
17,2013-10-13 01:01:00,М.37 хочу общения с д/ж и не только. смс ммс з...,1,1,0
18,2016-01-19 22:33:00,Элегантная госпожа ищет мальчика на побегушках...,22,33,0
19,2014-03-17 23:16:00,МЗ9ПОЗНАК.СО СТРОЙНОЙ ДЕВ.С ДНЕПРА ДО З0 ДЛЯ С...,23,16,0
20,2014-06-11 00:12:00,парень познакомиться с.девушкой для серьёзных ...,0,12,0
21,2014-01-23 00:17:00,увезу Д до 20 за границу стройн красив Алексей,0,17,0
22,2015-02-18 00:34:00,ищю д-ж для и от30до60 сначала смс админ 226(0...,0,34,0
23,2013-09-10 00:06:00,ласковая кошечка ищет своего ночного котика,0,6,0
24,2013-03-18 02:00:00,Мар Володя,2,0,0